### ISSUE TITLE
Some issues with the inference example notebook

### ISSUE THREAD

**Issue by hysts** [amazon-research/gan-control#1]
Hi, thank you for sharing this awesome work!

I am trying to run the inference example notebook, but I got some issues.

1. I think the notebook expects `src` to be in the `PYTHONPATH`, so `sys.path.append('../src')` is needed.
2. In the second cell, `from models.controller import Controller` should be changed to `from gan_control.inference.controller import Controller`. The file `controller` is not in the `models` directory, but in `inference` directory.
3. In the 12th cell, there's a line `from utils.spherical_harmonics_utils import sh_eval_basis_1`, but the file seems to be missing in the `utils` directory.
4. In the 15th cell, there's a line `attributes_df = pd.read_pickle('resources/ffhq_1K_attributes_samples_df.pkl')`, but the file `ffhq_1K_attributes_samples_df.pkl` is missing and not mentioned in the `README.md`, either.

**Comment by plaidam** [comment]
Ran into similar issues as above. 

Also if a colab could be supplied that would be greatly appreciated.

**Comment by AlonShoshan10** [comment]
Thanks for raising the issues. We will fix them in the coming days.

**Comment by nemo0526** [comment]
Hello guts ,have you met ' No module named 'gan_control.models.op'' problem?

**Comment by hysts** [comment]
@nemo0526 
No, I haven't. As @AlonShoshan10 fixed the issues 1-3 mentioned above in 0613c36, now I can run the notebook as is up to the 14th cell in my environment.

**Comment by AlonShoshan10** [comment]
The notebook should run now until the end. Thanks for your comments.

nemo0526 where do you encounter "No module named 'gan_control.models.op'"?

**Comment by hysts** [comment]
@AlonShoshan10 Great! Thank you very much.
